import Head from 'next/head'
import { test } from '../controls/useAuth'
import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
       
      </Head>
      <h1>
        KENAL
      </h1>
<button onClick={test}>login with google</button>
    </div>
  )
}
